<?php
/**
 * EsignApi
 * PHP version 7.4
 *
 * @category Class
 * @package  BBSPJIKKP\Sdk\Esign
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * TTE Service
 *
 * This API is used for sending whatsapp via API
 *
 * The version of the OpenAPI document: 1.0.8
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.8.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace BBSPJIKKP\Sdk\Esign\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use BBSPJIKKP\Sdk\Esign\ApiException;
use BBSPJIKKP\Sdk\Esign\Configuration;
use BBSPJIKKP\Sdk\Esign\HeaderSelector;
use BBSPJIKKP\Sdk\Esign\ObjectSerializer;

/**
 * EsignApi Class Doc Comment
 *
 * @category Class
 * @package  BBSPJIKKP\Sdk\Esign
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EsignApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getUserNik' => [
            'application/json',
        ],
        'signDocument' => [
            'multipart/form-data',
        ],
        'verifyDocumentByDoc' => [
            'multipart/form-data',
        ],
        'verifyDocumentById' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getUserNik
     *
     * Get user information
     *
     * @param  string $nik NIK, Nomor Induk Kepegawaian (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getUserNik'] to see the possible values for this operation
     *
     * @throws \BBSPJIKKP\Sdk\Esign\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \BBSPJIKKP\Sdk\Esign\Model\GetUserNik200Response
     */
    public function getUserNik($nik, string $contentType = self::contentTypes['getUserNik'][0])
    {
        list($response) = $this->getUserNikWithHttpInfo($nik, $contentType);
        return $response;
    }

    /**
     * Operation getUserNikWithHttpInfo
     *
     * Get user information
     *
     * @param  string $nik NIK, Nomor Induk Kepegawaian (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getUserNik'] to see the possible values for this operation
     *
     * @throws \BBSPJIKKP\Sdk\Esign\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \BBSPJIKKP\Sdk\Esign\Model\GetUserNik200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function getUserNikWithHttpInfo($nik, string $contentType = self::contentTypes['getUserNik'][0])
    {
        $request = $this->getUserNikRequest($nik, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\BBSPJIKKP\Sdk\Esign\Model\GetUserNik200Response' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\BBSPJIKKP\Sdk\Esign\Model\GetUserNik200Response' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\BBSPJIKKP\Sdk\Esign\Model\GetUserNik200Response', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\BBSPJIKKP\Sdk\Esign\Model\GetUserNik200Response';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BBSPJIKKP\Sdk\Esign\Model\GetUserNik200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getUserNikAsync
     *
     * Get user information
     *
     * @param  string $nik NIK, Nomor Induk Kepegawaian (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getUserNik'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getUserNikAsync($nik, string $contentType = self::contentTypes['getUserNik'][0])
    {
        return $this->getUserNikAsyncWithHttpInfo($nik, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getUserNikAsyncWithHttpInfo
     *
     * Get user information
     *
     * @param  string $nik NIK, Nomor Induk Kepegawaian (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getUserNik'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getUserNikAsyncWithHttpInfo($nik, string $contentType = self::contentTypes['getUserNik'][0])
    {
        $returnType = '\BBSPJIKKP\Sdk\Esign\Model\GetUserNik200Response';
        $request = $this->getUserNikRequest($nik, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getUserNik'
     *
     * @param  string $nik NIK, Nomor Induk Kepegawaian (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getUserNik'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getUserNikRequest($nik, string $contentType = self::contentTypes['getUserNik'][0])
    {

        // verify the required parameter 'nik' is set
        if ($nik === null || (is_array($nik) && count($nik) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $nik when calling getUserNik'
            );
        }


        $resourcePath = '/api/esign/nik/{nik}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($nik !== null) {
            $resourcePath = str_replace(
                '{' . 'nik' . '}',
                ObjectSerializer::toPathValue($nik),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-KEY');
        if ($apiKey !== null) {
            $headers['X-API-KEY'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation signDocument
     *
     * Add signature to a document
     *
     * @param  \SplFileObject $file file (required)
     * @param  string $nik nik (required)
     * @param  string $passphrase passphrase (required)
     * @param  string $ref_code Reference code adalah nomor unik disetiap layanan untuk verifikasi dokumen (required)
     * @param  string $file_name file_name (optional)
     * @param  string $ref_metadata Metadata tambahan untuk verifikasi dokumen dalam format JSON yang di encode base64 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['signDocument'] to see the possible values for this operation
     *
     * @throws \BBSPJIKKP\Sdk\Esign\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \BBSPJIKKP\Sdk\Esign\Model\SignResponse
     */
    public function signDocument($file, $nik, $passphrase, $ref_code, $file_name = null, $ref_metadata = null, string $contentType = self::contentTypes['signDocument'][0])
    {
        list($response) = $this->signDocumentWithHttpInfo($file, $nik, $passphrase, $ref_code, $file_name, $ref_metadata, $contentType);
        return $response;
    }

    /**
     * Operation signDocumentWithHttpInfo
     *
     * Add signature to a document
     *
     * @param  \SplFileObject $file (required)
     * @param  string $nik (required)
     * @param  string $passphrase (required)
     * @param  string $ref_code Reference code adalah nomor unik disetiap layanan untuk verifikasi dokumen (required)
     * @param  string $file_name (optional)
     * @param  string $ref_metadata Metadata tambahan untuk verifikasi dokumen dalam format JSON yang di encode base64 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['signDocument'] to see the possible values for this operation
     *
     * @throws \BBSPJIKKP\Sdk\Esign\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \BBSPJIKKP\Sdk\Esign\Model\SignResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function signDocumentWithHttpInfo($file, $nik, $passphrase, $ref_code, $file_name = null, $ref_metadata = null, string $contentType = self::contentTypes['signDocument'][0])
    {
        $request = $this->signDocumentRequest($file, $nik, $passphrase, $ref_code, $file_name, $ref_metadata, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\BBSPJIKKP\Sdk\Esign\Model\SignResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\BBSPJIKKP\Sdk\Esign\Model\SignResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\BBSPJIKKP\Sdk\Esign\Model\SignResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\BBSPJIKKP\Sdk\Esign\Model\SignResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BBSPJIKKP\Sdk\Esign\Model\SignResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation signDocumentAsync
     *
     * Add signature to a document
     *
     * @param  \SplFileObject $file (required)
     * @param  string $nik (required)
     * @param  string $passphrase (required)
     * @param  string $ref_code Reference code adalah nomor unik disetiap layanan untuk verifikasi dokumen (required)
     * @param  string $file_name (optional)
     * @param  string $ref_metadata Metadata tambahan untuk verifikasi dokumen dalam format JSON yang di encode base64 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['signDocument'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function signDocumentAsync($file, $nik, $passphrase, $ref_code, $file_name = null, $ref_metadata = null, string $contentType = self::contentTypes['signDocument'][0])
    {
        return $this->signDocumentAsyncWithHttpInfo($file, $nik, $passphrase, $ref_code, $file_name, $ref_metadata, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation signDocumentAsyncWithHttpInfo
     *
     * Add signature to a document
     *
     * @param  \SplFileObject $file (required)
     * @param  string $nik (required)
     * @param  string $passphrase (required)
     * @param  string $ref_code Reference code adalah nomor unik disetiap layanan untuk verifikasi dokumen (required)
     * @param  string $file_name (optional)
     * @param  string $ref_metadata Metadata tambahan untuk verifikasi dokumen dalam format JSON yang di encode base64 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['signDocument'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function signDocumentAsyncWithHttpInfo($file, $nik, $passphrase, $ref_code, $file_name = null, $ref_metadata = null, string $contentType = self::contentTypes['signDocument'][0])
    {
        $returnType = '\BBSPJIKKP\Sdk\Esign\Model\SignResponse';
        $request = $this->signDocumentRequest($file, $nik, $passphrase, $ref_code, $file_name, $ref_metadata, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'signDocument'
     *
     * @param  \SplFileObject $file (required)
     * @param  string $nik (required)
     * @param  string $passphrase (required)
     * @param  string $ref_code Reference code adalah nomor unik disetiap layanan untuk verifikasi dokumen (required)
     * @param  string $file_name (optional)
     * @param  string $ref_metadata Metadata tambahan untuk verifikasi dokumen dalam format JSON yang di encode base64 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['signDocument'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function signDocumentRequest($file, $nik, $passphrase, $ref_code, $file_name = null, $ref_metadata = null, string $contentType = self::contentTypes['signDocument'][0])
    {

        // verify the required parameter 'file' is set
        if ($file === null || (is_array($file) && count($file) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $file when calling signDocument'
            );
        }

        // verify the required parameter 'nik' is set
        if ($nik === null || (is_array($nik) && count($nik) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $nik when calling signDocument'
            );
        }

        // verify the required parameter 'passphrase' is set
        if ($passphrase === null || (is_array($passphrase) && count($passphrase) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $passphrase when calling signDocument'
            );
        }

        // verify the required parameter 'ref_code' is set
        if ($ref_code === null || (is_array($ref_code) && count($ref_code) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $ref_code when calling signDocument'
            );
        }




        $resourcePath = '/api/esign/sign';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;




        // form params
        if ($file !== null) {
            $multipart = true;
            $formParams['file'] = [];
            $paramFiles = is_array($file) ? $file : [$file];
            foreach ($paramFiles as $paramFile) {
                $formParams['file'][] = \GuzzleHttp\Psr7\Utils::tryFopen(
                    ObjectSerializer::toFormValue($paramFile),
                    'rb'
                );
            }
        }
        // form params
        if ($file_name !== null) {
            $formParams['file_name'] = ObjectSerializer::toFormValue($file_name);
        }
        // form params
        if ($nik !== null) {
            $formParams['nik'] = ObjectSerializer::toFormValue($nik);
        }
        // form params
        if ($passphrase !== null) {
            $formParams['passphrase'] = ObjectSerializer::toFormValue($passphrase);
        }
        // form params
        if ($ref_code !== null) {
            $formParams['ref_code'] = ObjectSerializer::toFormValue($ref_code);
        }
        // form params
        if ($ref_metadata !== null) {
            $formParams['ref_metadata'] = ObjectSerializer::toFormValue($ref_metadata);
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-KEY');
        if ($apiKey !== null) {
            $headers['X-API-KEY'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation verifyDocumentByDoc
     *
     * Verify signature
     *
     * @param  \SplFileObject $signed_file signed_file (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['verifyDocumentByDoc'] to see the possible values for this operation
     *
     * @throws \BBSPJIKKP\Sdk\Esign\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \BBSPJIKKP\Sdk\Esign\Model\EsignResult
     */
    public function verifyDocumentByDoc($signed_file, string $contentType = self::contentTypes['verifyDocumentByDoc'][0])
    {
        list($response) = $this->verifyDocumentByDocWithHttpInfo($signed_file, $contentType);
        return $response;
    }

    /**
     * Operation verifyDocumentByDocWithHttpInfo
     *
     * Verify signature
     *
     * @param  \SplFileObject $signed_file (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['verifyDocumentByDoc'] to see the possible values for this operation
     *
     * @throws \BBSPJIKKP\Sdk\Esign\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \BBSPJIKKP\Sdk\Esign\Model\EsignResult, HTTP status code, HTTP response headers (array of strings)
     */
    public function verifyDocumentByDocWithHttpInfo($signed_file, string $contentType = self::contentTypes['verifyDocumentByDoc'][0])
    {
        $request = $this->verifyDocumentByDocRequest($signed_file, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\BBSPJIKKP\Sdk\Esign\Model\EsignResult' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\BBSPJIKKP\Sdk\Esign\Model\EsignResult' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\BBSPJIKKP\Sdk\Esign\Model\EsignResult', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\BBSPJIKKP\Sdk\Esign\Model\EsignResult';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BBSPJIKKP\Sdk\Esign\Model\EsignResult',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation verifyDocumentByDocAsync
     *
     * Verify signature
     *
     * @param  \SplFileObject $signed_file (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['verifyDocumentByDoc'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function verifyDocumentByDocAsync($signed_file, string $contentType = self::contentTypes['verifyDocumentByDoc'][0])
    {
        return $this->verifyDocumentByDocAsyncWithHttpInfo($signed_file, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation verifyDocumentByDocAsyncWithHttpInfo
     *
     * Verify signature
     *
     * @param  \SplFileObject $signed_file (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['verifyDocumentByDoc'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function verifyDocumentByDocAsyncWithHttpInfo($signed_file, string $contentType = self::contentTypes['verifyDocumentByDoc'][0])
    {
        $returnType = '\BBSPJIKKP\Sdk\Esign\Model\EsignResult';
        $request = $this->verifyDocumentByDocRequest($signed_file, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'verifyDocumentByDoc'
     *
     * @param  \SplFileObject $signed_file (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['verifyDocumentByDoc'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function verifyDocumentByDocRequest($signed_file, string $contentType = self::contentTypes['verifyDocumentByDoc'][0])
    {

        // verify the required parameter 'signed_file' is set
        if ($signed_file === null || (is_array($signed_file) && count($signed_file) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $signed_file when calling verifyDocumentByDoc'
            );
        }


        $resourcePath = '/api/esign/verify/doc';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;




        // form params
        if ($signed_file !== null) {
            $multipart = true;
            $formParams['signed_file'] = [];
            $paramFiles = is_array($signed_file) ? $signed_file : [$signed_file];
            foreach ($paramFiles as $paramFile) {
                $formParams['signed_file'][] = \GuzzleHttp\Psr7\Utils::tryFopen(
                    ObjectSerializer::toFormValue($paramFile),
                    'rb'
                );
            }
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-KEY');
        if ($apiKey !== null) {
            $headers['X-API-KEY'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation verifyDocumentById
     *
     * Verify signature
     *
     * @param  string $id Esign ID / Reference Code (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['verifyDocumentById'] to see the possible values for this operation
     *
     * @throws \BBSPJIKKP\Sdk\Esign\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \BBSPJIKKP\Sdk\Esign\Model\EsignResult
     */
    public function verifyDocumentById($id, string $contentType = self::contentTypes['verifyDocumentById'][0])
    {
        list($response) = $this->verifyDocumentByIdWithHttpInfo($id, $contentType);
        return $response;
    }

    /**
     * Operation verifyDocumentByIdWithHttpInfo
     *
     * Verify signature
     *
     * @param  string $id Esign ID / Reference Code (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['verifyDocumentById'] to see the possible values for this operation
     *
     * @throws \BBSPJIKKP\Sdk\Esign\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \BBSPJIKKP\Sdk\Esign\Model\EsignResult, HTTP status code, HTTP response headers (array of strings)
     */
    public function verifyDocumentByIdWithHttpInfo($id, string $contentType = self::contentTypes['verifyDocumentById'][0])
    {
        $request = $this->verifyDocumentByIdRequest($id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\BBSPJIKKP\Sdk\Esign\Model\EsignResult' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\BBSPJIKKP\Sdk\Esign\Model\EsignResult' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\BBSPJIKKP\Sdk\Esign\Model\EsignResult', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\BBSPJIKKP\Sdk\Esign\Model\EsignResult';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BBSPJIKKP\Sdk\Esign\Model\EsignResult',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation verifyDocumentByIdAsync
     *
     * Verify signature
     *
     * @param  string $id Esign ID / Reference Code (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['verifyDocumentById'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function verifyDocumentByIdAsync($id, string $contentType = self::contentTypes['verifyDocumentById'][0])
    {
        return $this->verifyDocumentByIdAsyncWithHttpInfo($id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation verifyDocumentByIdAsyncWithHttpInfo
     *
     * Verify signature
     *
     * @param  string $id Esign ID / Reference Code (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['verifyDocumentById'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function verifyDocumentByIdAsyncWithHttpInfo($id, string $contentType = self::contentTypes['verifyDocumentById'][0])
    {
        $returnType = '\BBSPJIKKP\Sdk\Esign\Model\EsignResult';
        $request = $this->verifyDocumentByIdRequest($id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'verifyDocumentById'
     *
     * @param  string $id Esign ID / Reference Code (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['verifyDocumentById'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function verifyDocumentByIdRequest($id, string $contentType = self::contentTypes['verifyDocumentById'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling verifyDocumentById'
            );
        }


        $resourcePath = '/api/esign/verify/id';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $id,
            'id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-KEY');
        if ($apiKey !== null) {
            $headers['X-API-KEY'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
