/*
TTE Service

This API is used for sending whatsapp via API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk-esign-service

import (
	"encoding/json"
)

// checks if the EsignDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EsignDetails{}

// EsignDetails struct for EsignDetails
type EsignDetails struct {
	NamaDokumen *string `json:"nama_dokumen,omitempty"`
	JumlahSignature *int32 `json:"jumlah_signature,omitempty"`
	Notes *string `json:"notes,omitempty"`
	Details []SignatureDetail `json:"details,omitempty"`
	Summary *string `json:"summary,omitempty"`
}

// NewEsignDetails instantiates a new EsignDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEsignDetails() *EsignDetails {
	this := EsignDetails{}
	return &this
}

// NewEsignDetailsWithDefaults instantiates a new EsignDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEsignDetailsWithDefaults() *EsignDetails {
	this := EsignDetails{}
	return &this
}

// GetNamaDokumen returns the NamaDokumen field value if set, zero value otherwise.
func (o *EsignDetails) GetNamaDokumen() string {
	if o == nil || IsNil(o.NamaDokumen) {
		var ret string
		return ret
	}
	return *o.NamaDokumen
}

// GetNamaDokumenOk returns a tuple with the NamaDokumen field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EsignDetails) GetNamaDokumenOk() (*string, bool) {
	if o == nil || IsNil(o.NamaDokumen) {
		return nil, false
	}
	return o.NamaDokumen, true
}

// HasNamaDokumen returns a boolean if a field has been set.
func (o *EsignDetails) HasNamaDokumen() bool {
	if o != nil && !IsNil(o.NamaDokumen) {
		return true
	}

	return false
}

// SetNamaDokumen gets a reference to the given string and assigns it to the NamaDokumen field.
func (o *EsignDetails) SetNamaDokumen(v string) {
	o.NamaDokumen = &v
}

// GetJumlahSignature returns the JumlahSignature field value if set, zero value otherwise.
func (o *EsignDetails) GetJumlahSignature() int32 {
	if o == nil || IsNil(o.JumlahSignature) {
		var ret int32
		return ret
	}
	return *o.JumlahSignature
}

// GetJumlahSignatureOk returns a tuple with the JumlahSignature field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EsignDetails) GetJumlahSignatureOk() (*int32, bool) {
	if o == nil || IsNil(o.JumlahSignature) {
		return nil, false
	}
	return o.JumlahSignature, true
}

// HasJumlahSignature returns a boolean if a field has been set.
func (o *EsignDetails) HasJumlahSignature() bool {
	if o != nil && !IsNil(o.JumlahSignature) {
		return true
	}

	return false
}

// SetJumlahSignature gets a reference to the given int32 and assigns it to the JumlahSignature field.
func (o *EsignDetails) SetJumlahSignature(v int32) {
	o.JumlahSignature = &v
}

// GetNotes returns the Notes field value if set, zero value otherwise.
func (o *EsignDetails) GetNotes() string {
	if o == nil || IsNil(o.Notes) {
		var ret string
		return ret
	}
	return *o.Notes
}

// GetNotesOk returns a tuple with the Notes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EsignDetails) GetNotesOk() (*string, bool) {
	if o == nil || IsNil(o.Notes) {
		return nil, false
	}
	return o.Notes, true
}

// HasNotes returns a boolean if a field has been set.
func (o *EsignDetails) HasNotes() bool {
	if o != nil && !IsNil(o.Notes) {
		return true
	}

	return false
}

// SetNotes gets a reference to the given string and assigns it to the Notes field.
func (o *EsignDetails) SetNotes(v string) {
	o.Notes = &v
}

// GetDetails returns the Details field value if set, zero value otherwise.
func (o *EsignDetails) GetDetails() []SignatureDetail {
	if o == nil || IsNil(o.Details) {
		var ret []SignatureDetail
		return ret
	}
	return o.Details
}

// GetDetailsOk returns a tuple with the Details field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EsignDetails) GetDetailsOk() ([]SignatureDetail, bool) {
	if o == nil || IsNil(o.Details) {
		return nil, false
	}
	return o.Details, true
}

// HasDetails returns a boolean if a field has been set.
func (o *EsignDetails) HasDetails() bool {
	if o != nil && !IsNil(o.Details) {
		return true
	}

	return false
}

// SetDetails gets a reference to the given []SignatureDetail and assigns it to the Details field.
func (o *EsignDetails) SetDetails(v []SignatureDetail) {
	o.Details = v
}

// GetSummary returns the Summary field value if set, zero value otherwise.
func (o *EsignDetails) GetSummary() string {
	if o == nil || IsNil(o.Summary) {
		var ret string
		return ret
	}
	return *o.Summary
}

// GetSummaryOk returns a tuple with the Summary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EsignDetails) GetSummaryOk() (*string, bool) {
	if o == nil || IsNil(o.Summary) {
		return nil, false
	}
	return o.Summary, true
}

// HasSummary returns a boolean if a field has been set.
func (o *EsignDetails) HasSummary() bool {
	if o != nil && !IsNil(o.Summary) {
		return true
	}

	return false
}

// SetSummary gets a reference to the given string and assigns it to the Summary field.
func (o *EsignDetails) SetSummary(v string) {
	o.Summary = &v
}

func (o EsignDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EsignDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NamaDokumen) {
		toSerialize["nama_dokumen"] = o.NamaDokumen
	}
	if !IsNil(o.JumlahSignature) {
		toSerialize["jumlah_signature"] = o.JumlahSignature
	}
	if !IsNil(o.Notes) {
		toSerialize["notes"] = o.Notes
	}
	if !IsNil(o.Details) {
		toSerialize["details"] = o.Details
	}
	if !IsNil(o.Summary) {
		toSerialize["summary"] = o.Summary
	}
	return toSerialize, nil
}

type NullableEsignDetails struct {
	value *EsignDetails
	isSet bool
}

func (v NullableEsignDetails) Get() *EsignDetails {
	return v.value
}

func (v *NullableEsignDetails) Set(val *EsignDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableEsignDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableEsignDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEsignDetails(val *EsignDetails) *NullableEsignDetails {
	return &NullableEsignDetails{value: val, isSet: true}
}

func (v NullableEsignDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEsignDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


