/*
TTE Service

This API is used for sending whatsapp via API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk-esign-service

import (
	"encoding/json"
)

// checks if the ApiEsignNikNikGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiEsignNikNikGet200Response{}

// ApiEsignNikNikGet200Response struct for ApiEsignNikNikGet200Response
type ApiEsignNikNikGet200Response struct {
	Results *bool `json:"results,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewApiEsignNikNikGet200Response instantiates a new ApiEsignNikNikGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiEsignNikNikGet200Response() *ApiEsignNikNikGet200Response {
	this := ApiEsignNikNikGet200Response{}
	return &this
}

// NewApiEsignNikNikGet200ResponseWithDefaults instantiates a new ApiEsignNikNikGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiEsignNikNikGet200ResponseWithDefaults() *ApiEsignNikNikGet200Response {
	this := ApiEsignNikNikGet200Response{}
	return &this
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *ApiEsignNikNikGet200Response) GetResults() bool {
	if o == nil || IsNil(o.Results) {
		var ret bool
		return ret
	}
	return *o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiEsignNikNikGet200Response) GetResultsOk() (*bool, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *ApiEsignNikNikGet200Response) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given bool and assigns it to the Results field.
func (o *ApiEsignNikNikGet200Response) SetResults(v bool) {
	o.Results = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ApiEsignNikNikGet200Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiEsignNikNikGet200Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ApiEsignNikNikGet200Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ApiEsignNikNikGet200Response) SetMessage(v string) {
	o.Message = &v
}

func (o ApiEsignNikNikGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiEsignNikNikGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableApiEsignNikNikGet200Response struct {
	value *ApiEsignNikNikGet200Response
	isSet bool
}

func (v NullableApiEsignNikNikGet200Response) Get() *ApiEsignNikNikGet200Response {
	return v.value
}

func (v *NullableApiEsignNikNikGet200Response) Set(val *ApiEsignNikNikGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiEsignNikNikGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiEsignNikNikGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiEsignNikNikGet200Response(val *ApiEsignNikNikGet200Response) *NullableApiEsignNikNikGet200Response {
	return &NullableApiEsignNikNikGet200Response{value: val, isSet: true}
}

func (v NullableApiEsignNikNikGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiEsignNikNikGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


