/*
TTE Service

This API is used for sending whatsapp via API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk-esign-service

import (
	"encoding/json"
)

// checks if the SignResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SignResponse{}

// SignResponse struct for SignResponse
type SignResponse struct {
	Message *string `json:"message,omitempty"`
	Results *SignResponseResults `json:"results,omitempty"`
}

// NewSignResponse instantiates a new SignResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSignResponse() *SignResponse {
	this := SignResponse{}
	return &this
}

// NewSignResponseWithDefaults instantiates a new SignResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSignResponseWithDefaults() *SignResponse {
	this := SignResponse{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *SignResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *SignResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *SignResponse) SetMessage(v string) {
	o.Message = &v
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *SignResponse) GetResults() SignResponseResults {
	if o == nil || IsNil(o.Results) {
		var ret SignResponseResults
		return ret
	}
	return *o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignResponse) GetResultsOk() (*SignResponseResults, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *SignResponse) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given SignResponseResults and assigns it to the Results field.
func (o *SignResponse) SetResults(v SignResponseResults) {
	o.Results = &v
}

func (o SignResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SignResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}
	return toSerialize, nil
}

type NullableSignResponse struct {
	value *SignResponse
	isSet bool
}

func (v NullableSignResponse) Get() *SignResponse {
	return v.value
}

func (v *NullableSignResponse) Set(val *SignResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSignResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSignResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSignResponse(val *SignResponse) *NullableSignResponse {
	return &NullableSignResponse{value: val, isSet: true}
}

func (v NullableSignResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSignResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


