<?php
/**
 * InfoSigner
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * TTE Service
 *
 * This API is used for sending whatsapp via API
 *
 * The version of the OpenAPI document: 1.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.8.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * InfoSigner Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class InfoSigner implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'InfoSigner';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'issuer_dn' => 'string',
        'signer_name' => 'string',
        'signer_cert_validity' => 'string',
        'signer_dn' => 'string',
        'cert_user_certified' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'issuer_dn' => null,
        'signer_name' => null,
        'signer_cert_validity' => null,
        'signer_dn' => null,
        'cert_user_certified' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'issuer_dn' => false,
        'signer_name' => false,
        'signer_cert_validity' => false,
        'signer_dn' => false,
        'cert_user_certified' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'issuer_dn' => 'issuer_dn',
        'signer_name' => 'signer_name',
        'signer_cert_validity' => 'signer_cert_validity',
        'signer_dn' => 'signer_dn',
        'cert_user_certified' => 'cert_user_certified'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'issuer_dn' => 'setIssuerDn',
        'signer_name' => 'setSignerName',
        'signer_cert_validity' => 'setSignerCertValidity',
        'signer_dn' => 'setSignerDn',
        'cert_user_certified' => 'setCertUserCertified'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'issuer_dn' => 'getIssuerDn',
        'signer_name' => 'getSignerName',
        'signer_cert_validity' => 'getSignerCertValidity',
        'signer_dn' => 'getSignerDn',
        'cert_user_certified' => 'getCertUserCertified'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('issuer_dn', $data ?? [], null);
        $this->setIfExists('signer_name', $data ?? [], null);
        $this->setIfExists('signer_cert_validity', $data ?? [], null);
        $this->setIfExists('signer_dn', $data ?? [], null);
        $this->setIfExists('cert_user_certified', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets issuer_dn
     *
     * @return string|null
     */
    public function getIssuerDn()
    {
        return $this->container['issuer_dn'];
    }

    /**
     * Sets issuer_dn
     *
     * @param string|null $issuer_dn issuer_dn
     *
     * @return self
     */
    public function setIssuerDn($issuer_dn)
    {
        if (is_null($issuer_dn)) {
            throw new \InvalidArgumentException('non-nullable issuer_dn cannot be null');
        }
        $this->container['issuer_dn'] = $issuer_dn;

        return $this;
    }

    /**
     * Gets signer_name
     *
     * @return string|null
     */
    public function getSignerName()
    {
        return $this->container['signer_name'];
    }

    /**
     * Sets signer_name
     *
     * @param string|null $signer_name signer_name
     *
     * @return self
     */
    public function setSignerName($signer_name)
    {
        if (is_null($signer_name)) {
            throw new \InvalidArgumentException('non-nullable signer_name cannot be null');
        }
        $this->container['signer_name'] = $signer_name;

        return $this;
    }

    /**
     * Gets signer_cert_validity
     *
     * @return string|null
     */
    public function getSignerCertValidity()
    {
        return $this->container['signer_cert_validity'];
    }

    /**
     * Sets signer_cert_validity
     *
     * @param string|null $signer_cert_validity signer_cert_validity
     *
     * @return self
     */
    public function setSignerCertValidity($signer_cert_validity)
    {
        if (is_null($signer_cert_validity)) {
            throw new \InvalidArgumentException('non-nullable signer_cert_validity cannot be null');
        }
        $this->container['signer_cert_validity'] = $signer_cert_validity;

        return $this;
    }

    /**
     * Gets signer_dn
     *
     * @return string|null
     */
    public function getSignerDn()
    {
        return $this->container['signer_dn'];
    }

    /**
     * Sets signer_dn
     *
     * @param string|null $signer_dn signer_dn
     *
     * @return self
     */
    public function setSignerDn($signer_dn)
    {
        if (is_null($signer_dn)) {
            throw new \InvalidArgumentException('non-nullable signer_dn cannot be null');
        }
        $this->container['signer_dn'] = $signer_dn;

        return $this;
    }

    /**
     * Gets cert_user_certified
     *
     * @return bool|null
     */
    public function getCertUserCertified()
    {
        return $this->container['cert_user_certified'];
    }

    /**
     * Sets cert_user_certified
     *
     * @param bool|null $cert_user_certified cert_user_certified
     *
     * @return self
     */
    public function setCertUserCertified($cert_user_certified)
    {
        if (is_null($cert_user_certified)) {
            throw new \InvalidArgumentException('non-nullable cert_user_certified cannot be null');
        }
        $this->container['cert_user_certified'] = $cert_user_certified;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


