<?php
/**
 * EsignResultResultsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * TTE Service
 *
 * This API is used for sending whatsapp via API
 *
 * OpenAPI spec version: 1.0.8
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

/**
 * EsignResultResultsTest Class Doc Comment
 *
 * @category    Class
 * @description EsignResultResults
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class EsignResultResultsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EsignResultResults"
     */
    public function testEsignResultResults()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "layanan"
     */
    public function testPropertyLayanan()
    {
    }

    /**
     * Test attribute "ref_code"
     */
    public function testPropertyRefCode()
    {
    }

    /**
     * Test attribute "ref_metadata"
     */
    public function testPropertyRefMetadata()
    {
    }

    /**
     * Test attribute "file_name"
     */
    public function testPropertyFileName()
    {
    }

    /**
     * Test attribute "file_link"
     */
    public function testPropertyFileLink()
    {
    }

    /**
     * Test attribute "date_signed"
     */
    public function testPropertyDateSigned()
    {
    }

    /**
     * Test attribute "esign_details"
     */
    public function testPropertyEsignDetails()
    {
    }
}
