<?php
/**
 * InfoSignerTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * TTE Service
 *
 * This API is used for sending whatsapp via API
 *
 * OpenAPI spec version: 1.0.8
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

/**
 * InfoSignerTest Class Doc Comment
 *
 * @category    Class
 * @description InfoSigner
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class InfoSignerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InfoSigner"
     */
    public function testInfoSigner()
    {
    }

    /**
     * Test attribute "issuer_dn"
     */
    public function testPropertyIssuerDn()
    {
    }

    /**
     * Test attribute "signer_name"
     */
    public function testPropertySignerName()
    {
    }

    /**
     * Test attribute "signer_cert_validity"
     */
    public function testPropertySignerCertValidity()
    {
    }

    /**
     * Test attribute "signer_dn"
     */
    public function testPropertySignerDn()
    {
    }

    /**
     * Test attribute "cert_user_certified"
     */
    public function testPropertyCertUserCertified()
    {
    }
}
