<?php
/**
 * SignatureDetailTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * TTE Service
 *
 * This API is used for sending whatsapp via API
 *
 * OpenAPI spec version: 1.0.8
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

/**
 * SignatureDetailTest Class Doc Comment
 *
 * @category    Class
 * @description SignatureDetail
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SignatureDetailTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SignatureDetail"
     */
    public function testSignatureDetail()
    {
    }

    /**
     * Test attribute "info_tsa"
     */
    public function testPropertyInfoTsa()
    {
    }

    /**
     * Test attribute "signature_field"
     */
    public function testPropertySignatureField()
    {
    }

    /**
     * Test attribute "info_signer"
     */
    public function testPropertyInfoSigner()
    {
    }

    /**
     * Test attribute "signature_document"
     */
    public function testPropertySignatureDocument()
    {
    }
}
