<?php
/**
 * EsignApiTest
 * PHP version 5
 *
 * @category Class
 * @package  BBSPJIKKP\Sdk\Esign
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * TTE Service
 *
 * This API is used for sending whatsapp via API
 *
 * The version of the OpenAPI document: 1.0.8
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace BBSPJIKKP\Sdk\Esign;

use \BBSPJIKKP\Sdk\Esign\Configuration;
use \BBSPJIKKP\Sdk\Esign\ApiException;
use \BBSPJIKKP\Sdk\Esign\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * EsignApiTest Class Doc Comment
 *
 * @category Class
 * @package  BBSPJIKKP\Sdk\Esign
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EsignApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getUserNik
     *
     * Get user information.
     *
     */
    public function testGetUserNik()
    {
    }

    /**
     * Test case for signDocument
     *
     * Add signature to a document.
     *
     */
    public function testSignDocument()
    {
    }

    /**
     * Test case for verifyDocumentByDoc
     *
     * Verify signature.
     *
     */
    public function testVerifyDocumentByDoc()
    {
    }

    /**
     * Test case for verifyDocumentById
     *
     * Verify signature.
     *
     */
    public function testVerifyDocumentById()
    {
    }
}
